on:
  push:
    branches:
      - main

jobs:
  update-translations-progress:
    name: Display translations progress inside readme.md
    runs-on: ubuntu-latest
    permissions:
      contents: write

    if: github.actor != 'roules-bot'
    steps:
      - name: update translations step
        id: hello
        uses: roules-dev/update-translation-progress-action@main
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          readme-path: readme.md
